import { useRouter } from 'next/router'; // add this line at the top
import type { NextPage } from 'next';
import Head from 'next/head';
import { useUser } from '@clerk/nextjs';
import { LoadingPage } from '~/components/ReusableElements/loading';
import { PageLayout } from '~/components/layout';
import BackButton from '~/components/ReusableElements/BackButton';
import { InfiniteScrollSearchResults } from '~/components/PostFeeds/infiniteScrollSearchResults';




const SearchResults: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn, user } = useUser();

  const router = useRouter(); // add this line

  const username = user?.username;

  // We can use router.query to fetch the 'q' parameter from the URL
  const searchQuery = router.query.q;

  // Return empty div if BOTH are not loaded, since user tends to load faster
  if (!userLoaded) return <LoadingPage />;

  if (isSignedIn && !username) return <div></div>;

  return (
    <>
      <Head>
        <title>{`Search - Placeholder`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
      <div className="mb-12 flex flex-col sticky top-0 z-50 backdrop-blur-sm">
      <BackButton />
    <ul className='flex flex-row justify-between text-center cursor-pointer mt-[72px]'>
        <li className='px-4 py-2 hover:bg-slate-700 w-full'>Top</li>
        <li className='px-4 py-2 hover:bg-slate-700 w-full'>Latest</li>
        <li className='px-4 py-2 hover:bg-slate-700 w-full'>People</li>
        <li className='px-4 py-2 hover:bg-slate-700 w-full'>Photos</li>
        <li className='px-4 py-2 hover:bg-slate-700 w-full'>Gifs</li>
      </ul>
      </div>


        <h1 className="text-2xl border-t border-slate-400 font-bold text-center pt-2">{`Search Results for "${searchQuery as string}"`}</h1>
        <InfiniteScrollSearchResults query={searchQuery as string}/>
      </PageLayout>
    </>
  );
};

export default SearchResults;
