name: CI

on: [push, pull_request]

env: # Define environment variables here
  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL}}
  CLOUDINARY_CLOUD_NAME: "your_cloud_name"
  CLOUDINARY_API_KEY: "your_api_key"
  CLOUDINARY_API_SECRET: "your_api_secret"
  CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: "/"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: "/"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Print Environment Variable
        run: echo $DATABASE_URL

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set a timeout
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Debug - Show Node Version
        run: node -v
      - name: Debug - Show NPM Version
        run: npm -v
      - name: Run Tests
        run: npm run workflow
